### ISSUE TITLE
hue functionality

### ISSUE THREAD

**Issue by slawira** [mscharley/colourist#12] opened 2016-03-31 02:49 UTC
would be great if the library also has function to increase and decrease hue.

**Comment by mscharley** [comment] 2016-03-31 05:27
See #15

**Comment by mscharley** [comment] 2016-03-31 05:54
Fixed and merged, will be in a release later tonight.

**Closed** 2016-03-31 05:54 UTC
Labels: enhancement

**Comment by mscharley** [comment] 2016-03-31 05:59
Also a duplicate of #6 ! Oh well.
